### ISSUE TITLE
Request collaborator access

### ISSUE THREAD

**Issue by dirkbonhomme** [demian85/gnip#10]
Hi @demian85 

There hasn't been much activity on this project for a while even though some PRs and issue reports are very useful. I think it would be sad if this project got scattered throughout many independent forks.

I'm willing to maintain this project if you allow me collaborator access? Or someone else if there's any interest?

Let me know what you think!

Thanks

**Comment by demian85** [comment]
That's ok by me. Thanks for tagging me, I wouldn't have noticed any issue at all...
