### ISSUE TITLE
Todo: prepare 0.3.0 release

### ISSUE THREAD

**Issue by dirkbonhomme** [demian85/gnip#13]
With one open PR remaining it's time to work towards a 0.3.0 release and have it pushed to the npm repository.

Todo:
- ~~Wait for #7 to be ready and merged to master~~
- ~~Create 0.3.0 tag~~
- Publish tag to npm

**Comment by dirkbonhomme** [comment]
@demian85 I've created a 0.3.0 tag which includes all the latest fixes and such. However I'm unable to publish the changes to npmjs.org. Can you try to do that?

Or grant access to me on npmjs: https://docs.npmjs.com/cli/owner
(username is dirkbonhomme)

Thanks a lot! Hope you agree with all the changes.

**Comment by demian85** [comment]
Done! Thanks @dirkbonhomme, hope you find this lib useful. I'm not using Gnip anymore.

**Comment by dirkbonhomme** [comment]
Thanks. I've been looking into multiple Gnip libraries but this one was the most promising. A few minor issues aside it's been running great for over 3 months now.
