### ISSUE TITLE
Gnip API endpoint format

### ISSUE THREAD

**Issue by seonixx** [demian85/gnip#16]
Gnip API endpoint conventions seem to have changed. Might want to update the examples?

e.g. PowerTrack is now: https://gnip-stream.twitter.com/stream/powertrack/accounts/xxx/publishers/twitter/prod.json

and rules is now:
https://gnip-api.twitter.com/rules/powertrack/accounts/xxx/publishers/twitter/prod.json

**Comment by dirkbonhomme** [comment]
Thanks @seonixx 

I've updated the lib to use 2.0 exclusively and added these endpoints to the doc: https://github.com/demian85/gnip/commits/master
