### ISSUE TITLE
PowerTrack 2.0?

### ISSUE THREAD

**Issue by alphashuro** [demian85/gnip#17]
Has this been updated to use PowerTrack 2.0?

**Comment by dirkbonhomme** [comment]
The master branch contains a commit for 2.0 although I haven't used it myself yet: https://github.com/demian85/gnip/commit/4ffc14ad22fdf8e0430758d10208053005225194

I will start using and testing the 2.0 updates within a few months and update the docs + release a new version of this project if all goes well.

**Comment by dirkbonhomme** [comment]
@alphashuro  I've just released v1.0.0 which only supports PowerTrack 2.0. Please let me know if you encounter any issues.
