### ISSUE TITLE
tweet matching_rules id's are being rounded

### ISSUE THREAD

**Issue by TimAtTheBeach** [demian85/gnip#18]
I'm testing PowerTrack 2.0 and noticed in each tweet the matching_rules:id is being rounded. All the rules end in 00. Here is an example of the one of the tweets.  Any thoughts?

`"gnip" : {
			"matching_rules" : [{
					"tag" : "1956",
					"id" : 781250306873012200
				}
			]`

**Comment by dirkbonhomme** [comment]
The maximum integer value that JavaScript supports is 9007199254740991. Numbers bigger than that can result in precision errors.

Matching IDs are pretty useless like this. I'll contact Gnip to see if they're willing to change it into a string.

**Comment by dirkbonhomme** [comment]
@TimAtTheBeach I've released v1.0.3 which allows you to pass json-bigint as the JSON parser. This enables you to process the id as if it was a string.

Docs: https://github.com/demian85/gnip#optionsparser
