### ISSUE TITLE
Not working with Replay v2.0

### ISSUE THREAD

**Issue by TimAtTheBeach** [demian85/gnip#20]
Just tested it with replay v2.0 and doesn't work.  In index.js on line 89 is has this `path : streamUrl.path + '?' + qs,`.   If qs is null then it appends the ? to then end of the url which gnip then rejects as invalid.  

Try testing with replay with only url, user, and password options.

**Comment by dirkbonhomme** [comment]
Thanks for reporting this. I'll look into is asap.

**Comment by dirkbonhomme** [comment]
Sorry for the delay. Fixed in 1.0.4
