### ISSUE TITLE
rule.id json-bigint usage?

### ISSUE THREAD

**Issue by dreadjr** [demian85/gnip#21]
i asked gnip if they plan on adding id_str, like all the other twitter apis, no response yet.

**Comment by dirkbonhomme** [comment]
I also asked this question but don't think they are going to add this anytime soon. As a workaround I've added the `parser` option: https://github.com/demian85/gnip#optionsparser

**Comment by dreadjr** [comment]
I noticed that on the streaming api client but not on the Rules client.
That still uses JSON.parse. Obviously them to fix it, is the better
solution.

**Comment by tzellman** [comment]
I pushed a PR #24 which adds a similar `parser` option for use with the Rules API, which should resolve the issue if you specify `json-bigint` as your `parser` option in the Rules constructor.

**Comment by demian85** [comment]
Fixed.
