### ISSUE TITLE
Rule errors are not returned during bulk add

### ISSUE THREAD

**Issue by cttibbetts** [demian85/gnip#37]
It seems that when adding rules in bulk, errors are not carried on the `body.error` property, but rather in an array in `body.detail`. 

I think adding a clause for this possibility to append more information to the `errStr` is appropriate, something like this:
```
if (body && body.detail) {
    errStr = body.detail.filter(r => r.message).reduce((msg, r) =>
        msg + '\n' + r.message
    , errStr);
}
```
This would result in an error string like 
> Error: Unable to add rules. Request Failed with status code: 422
> Rule 'something' has some error

https://github.com/demian85/gnip/blob/master/lib/rules.js#L49

From the [GNIP docs](http://support.gnip.com/apis/powertrack/api_reference.html): 

422 | Unprocessable Entity | Generally occurs due to an invalid rule, based on the PowerTrack rule restrictions. Requests fail or succeed as a batch. For these errors, each invalid rule and the reason for rejection is included in a JSON message in the response. Catch the associated exception to expose this message.
-- | -- | --

**Comment by dirkbonhomme** [comment]
Are you using the latest version from npmjs.org? The most recent commit should format and return rule errors in the error. https://github.com/demian85/gnip/commit/ec37f9131094cf4b829f6727cd2f45b14c5c21e0

**Comment by cttibbetts** [comment]
I am using version 2.2.2, after cleaning my npm cache and pulling again, but for some reason I don't see the code from the change you linked in `lib/rules.js`. That said, when I look at the source code directly from github, it's there. Is there any chance those two sources aren't in sync?

**Comment by cttibbetts** [comment]
I also just had another person try it on another computer with the same results. They have never pulled your library before.

**Comment by demian85** [comment]
Nice, I just tried to publish to npm the latest changes, but I changed my
phone and lost my 2FA credentials. No clue how to get them back and they do
not support sms... :GENIUS:

**Comment by dirkbonhomme** [comment]
@demian85 auch 😱 Do they have some kind of support channel?

@cttibbetts I've just bumped the version and published v2.2.3 to npm. I think the npm version was not in sync with the git tag. Can you retry?

I'm not involved in any projects using Gnip anymore so I can't really support this project much longer. But hopefully this latest version helps you solve the issue :)

**Comment by cttibbetts** [comment]
The updated version has the code in question. I can't test it right now, but the code you shared definitely looks like it solves the issue. Thank you for the update! 👍

**Comment by cttibbetts** [comment]
Confirmed 2.2.3 fixes this issue.
