### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by dreadjr** [demian85/gnip#8]
There are a bunch of good pull requests that would be helpful in the pipeline.

**Comment by anddimario** [comment]
+1

**Comment by dirkbonhomme** [comment]
@dreadjr @anddimario I've been given collaborator access by @demian85 yesterday and he also merged some PR's while at it.
I'll try to verify all open PRs soon and merge them when everything looks good. Please update any pull requests or tickets you have and we'll try to include them in a next release.
